spring:
  profiles:
    active:
    - dev  #当前的使用环境
  
---
server:
  port: 6001
spring: 
  profiles: div #开发环境
  aplication:
    name: config-client-dev
eureka:
  cliet:
    service-url:
      defaultZone: http://localhost:1001/eureka/
     
---
server:
  port: 6002
spring: 
  profiles: test #测试环境
  aplication:
    name: config-client-test
eureka:
  cliet:
    service-url:
      defaultZone: http://localhost:1001/eureka/
